markdown: rdiscount
permalink: /:title/
baseurl: "http://elvis4gh.github.com/elvis_github_page"
wikiurl: "http://elvis4gh.github.com/elvis_github_page/wiki/html"
name: Elvis Chen
author: Elvis 
qq: 84880143 
email: cxmpersonal@gmail.com
duoshuo: elvis4ds 
#beian: 浙ICP备12026616号
cnzz: 119959
weibo: 328280959
github: elvis4gh 
pygments: true
safe: true
paginate: 20
about: "I am a designer, I am used to playing C++ for embedded system or access network. Thanks for joining us."
