markdown: rdiscount
permalink: /:title/
url: http://yonsm.net
name: Elvis Chen
author: Elvis 
qq: 84880143 
email: elvis4hm@hotmail.com
duoshuo: elvis4ds 
#beian: 浙ICP备12026616号
cnzz: 119959
weibo: 328280959
github: elvis4gh 
pygments: true
safe: true
paginate: 20
about: "Elvis's blog. Fork from Yonsm blog at github"
